"use client";
import { useState } from "react";
import { ArrowLeft, CheckCircle2, ClipboardCheck, Send } from "lucide-react";
import { listSubmissions, updateSubmission, type EssayGrade, type Submission } from "@/lib/submissions";

export default function EssayGradingHub({ onBack }: { onBack: () => void }) {
  const [items,setItems]=useState<Submission[]>(()=>listSubmissions());
  const [selected,setSelected]=useState<string|null>(()=>listSubmissions()[0]?.id??null);
  const current=items.find((item)=>item.id===selected);
  const refresh=()=>setItems(listSubmissions());
  const grade=(index:number, patch:Partial<EssayGrade>)=>{if(!current)return; const grades={...current.grades,[index]:{points:current.grades[index]?.points??0,feedback:current.grades[index]?.feedback??"",...patch}}; updateSubmission(current.id,{grades,status:"pending_review"}); refresh();};
  const essays=current?.quiz.questions.map((question,index)=>({question,index})).filter(({question})=>question.type==="essay")??[];
  const complete=!!current&&essays.every(({index})=>current.grades[index]&&current.grades[index].points>=0);
  const markGraded=()=>{if(current&&complete){updateSubmission(current.id,{status:"graded"});refresh();}};
  const publish=()=>{if(current&&current.status==="graded"){updateSubmission(current.id,{status:"published"});refresh();}};
  return <main className="mx-auto w-full max-w-6xl flex-1 p-4 sm:p-7"><header className="flex flex-wrap items-center justify-between gap-3 rounded-3xl bg-slate-900 p-5 text-white"><div><p className="text-xs font-black uppercase tracking-widest text-emerald-300">Kiểm soát kết quả</p><h1 className="mt-1 text-2xl font-black">Chấm tự luận & công bố điểm</h1></div><button onClick={onBack} className="inline-flex items-center gap-2 rounded-xl bg-white/10 px-4 py-3 text-sm font-bold"><ArrowLeft size={17}/>Ngân hàng đề</button></header>
    <div className="mt-4 grid gap-4 lg:grid-cols-[300px_1fr]"><aside className="rounded-3xl bg-white p-3 shadow-lg"><p className="p-2 text-xs font-black uppercase text-slate-500">Bài đã nộp ({items.length})</p>{items.length===0?<p className="p-4 text-sm text-slate-500">Chưa có bài nộp. Hãy làm thử một đề có câu tự luận.</p>:items.map((item)=><button key={item.id} onClick={()=>setSelected(item.id)} className={`mb-2 w-full rounded-2xl p-3 text-left ${selected===item.id?"bg-emerald-50 ring-2 ring-[#018f41]":"bg-slate-50"}`}><b className="block text-sm text-slate-900">{item.quizTitle}</b><span className="text-xs text-slate-500">{new Date(item.submittedAt).toLocaleString("vi-VN")}</span><span className={`mt-2 block text-xs font-black ${item.status==="published"?"text-emerald-700":"text-amber-700"}`}>{item.status==="published"?"ĐÃ CÔNG BỐ":item.status==="graded"?"ĐÃ CHẤM · CHỜ CÔNG BỐ":"CHỜ CHẤM"}</span></button>)}</aside>
      <section className="rounded-3xl bg-white p-5 shadow-lg">{!current?<div className="py-20 text-center text-slate-500"><ClipboardCheck className="mx-auto mb-3"/>Chọn một bài để chấm</div>:<><h2 className="text-xl font-black text-slate-900">{current.quizTitle}</h2><div className="mt-4 space-y-4">{essays.map(({question,index})=><article key={index} className="rounded-2xl border border-slate-200 p-4"><p className="font-bold text-slate-900">Câu {index+1}. {question.text}</p><p className="mt-3 whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm leading-6">{String(current.responses[index]??"(Không trả lời)")}</p><div className="mt-3 grid gap-3 sm:grid-cols-[160px_1fr]"><label className="text-xs font-bold text-slate-600">Điểm (tối đa {question.points})<input type="number" min={0} max={question.points} value={current.grades[index]?.points??""} onChange={(e)=>grade(index,{points:Math.min(question.points,Math.max(0,Number(e.target.value)))})} className="mt-1 min-h-11 w-full rounded-xl border p-2 text-base"/></label><label className="text-xs font-bold text-slate-600">Nhận xét<textarea value={current.grades[index]?.feedback??""} onChange={(e)=>grade(index,{feedback:e.target.value})} className="mt-1 min-h-20 w-full rounded-xl border p-2 text-sm"/></label></div></article>)}</div><div className="mt-5 flex flex-wrap justify-end gap-2"><button disabled={!complete||current.status!=="pending_review"} onClick={markGraded} className="inline-flex items-center gap-2 rounded-xl bg-[#018f41] px-4 py-3 text-sm font-black text-white disabled:opacity-40"><CheckCircle2 size={17}/>Hoàn tất chấm</button><button disabled={current.status!=="graded"} onClick={publish} className="inline-flex items-center gap-2 rounded-xl bg-[#f58220] px-4 py-3 text-sm font-black text-white disabled:opacity-40"><Send size={17}/>Công bố kết quả</button></div></>}</section></div>
  </main>;
}
